#
# University of Pisa - Advanced Software Engineering - 2021-2022
# Main docker-compose File
# Project:
#┌─────────────────────────────────────────────────────────────────────────────────────────┐ 
#│  __  __                                  _                 ____        _   _   _        │ 
#│ |  \/  | ___  ___ ___  __ _  __ _  ___  (_)_ __     __ _  | __ )  ___ | |_| |_| | ___   │
#│ | |\/| |/ _ \/ __/ __|/ _` |/ _` |/ _ \ | | '_ \   / _` | |  _ \ / _ \| __| __| |/ _ \  │
#│ | |  | |  __/\__ \__ \ (_| | (_| |  __/ | | | | | | (_| | | |_) | (_) | |_| |_| |  __/  │ 
#│ |_|  |_|\___||___/___/\__,_|\__, |\___| |_|_| |_|  \__,_| |____/ \___/ \__|\__|_|\___|  │ 
#│                              |___/                                                      │ 
#└─────────────────────────────────────────────────────────────────────────────────────────┘

version: '3.8'

services:

  # -------------------------------------------- #
  # Starting with API Gateway and Load Balancer  #
  # -------------------------------------------- #

  nginx_lb_orchestrator:
    #
    # Nginx Orchestrator instance
    #
    container_name: load_balancer_orchestrator
    restart: always
    build: ./api-gateway/nginx-orchestrator
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # WARNING: with Winzozz it does not work, but we need it!
      - nginx_conf:/etc/nginx/conf.d

  nginx_lb:
    #
    # Nginx single instance
    #
    container_name: load_balancer
    restart: always
    build: ./api-gateway/nginx
    labels:
      - mib.nginx_lb
    volumes:
      - nginx_conf:/etc/nginx/conf.d
      - static_contents:/static
    ports:
      - "80:80"

  api_gateway:
    #
    # API Gateway
    #
    # ! ! ! WARNING ! ! !
    # DO NOT set the container_name attribute and ports mapping
    # to allow the replication.
    #
    restart: always
    build: ./api-gateway
    volumes:
      - static_contents:/static
    env_file:
      - gateway.conf
    environment:
      - USERS_MS_HOST=users_ms_worker
      - LOTTERY_MS_HOST=lottery_ms_worker
      - MESSAGES_MS_HOST=messages_ms_worker
    labels:
      - mib.api_gateway_worker

  # -------------------------------------------- #
  # Common Services                              #
  # -------------------------------------------- #

  #
  # specify here the common services between your
  # microservices
  #


  # -------------------------------------------- #
  # Users Microservice                           #
  # -------------------------------------------- #
  users_ms_db:
    #
    # Users Microservice Database
    #
    image: library/postgres:10
    restart: on-failure
    env_file:
      - users_ms.conf
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER" ]
      interval: 10s
      timeout: 5s
      retries: 5

  users_ms_migrations:
    #
    # Users Microservice Migrations
    #
    build: ./mib-users
    env_file:
      - users_ms.conf
    environment:
      - POSTGRES_HOST=users_ms_db
    restart: on-failure
    command: flask db upgrade
    depends_on:
      users_ms_db:
        condition: service_healthy

  users_ms_worker:
    #
    # Users Microservice Worker node
    #
    build: ./mib-users
    restart: on-failure
    env_file:
      - users_ms.conf
    environment:
      - POSTGRES_HOST=users_ms_db
    depends_on:
      users_ms_db:
        condition: service_healthy
      users_ms_migrations:
        condition: service_started

  # -------------------------------------------- #
  # Lottery Microservice                         #
  # -------------------------------------------- #

  lottery_ms_db:
    #
    # Lottery Microservice Database
    #
    image: library/postgres:10
    restart: on-failure
    env_file:
      - lottery_ms.conf
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER" ]
      interval: 10s
      timeout: 5s
      retries: 5

  lottery_ms_migrations:
    #
    # Lottery Microservice Migrations
    #
    build: ./mib-lottery
    env_file:
      - lottery_ms.conf
    environment:
      - POSTGRES_HOST=lottery_ms_db
    restart: on-failure
    command: flask db upgrade
    depends_on:
      lottery_ms_db:
        condition: service_healthy

  lottery_ms_worker:
    #
    # Lottery Microservice Worker node
    #
    <<:
      &lottery_ms_worker
      build: ./mib-lottery
      restart: on-failure

    env_file:
      - lottery_ms.conf
    environment:
      - POSTGRES_HOST=lottery_ms_db
      - BROKER_URL=redis://redis_lottery
      - RESULT_BACKEND=redis://redis_lottery
    depends_on:
      - lottery_ms_db
      - lottery_ms_migrations
      - redis_lottery

  redis_lottery:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    expose:
      - "6379"

  celery_worker_lottery:
    <<: *lottery_ms_worker
    command:
      [
        'celery',
        '-A',
        'swagger_server.background',
        'worker',
        '--loglevel=INFO'
      ]
    env_file:
      - lottery_ms.conf
    environment:
      - POSTGRES_HOST=lottery_ms_db
      - BROKER_URL=redis://redis_lottery
      - RESULT_BACKEND=redis://redis_lottery
    depends_on:
      - lottery_ms_db
      - redis_lottery

  celery_beat_lottery:
    <<: *lottery_ms_worker
    command:
      [
        'celery',
        '-A',
        'swagger_server.background',
        'beat',
        '--loglevel=INFO'
      ]
    env_file:
      - lottery_ms.conf
    environment:
      - POSTGRES_HOST=lottery_ms_db
      - BROKER_URL=redis://redis_lottery
      - RESULT_BACKEND=redis://redis_lottery
    depends_on:
      - lottery_ms_db
      - redis_lottery

  # -------------------------------------------- #
  # Messages Microservice                         #
  # -------------------------------------------- #

  db_messages:
    image: postgres:13
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/db_messages/data
    ports:
      # this is only for development purpose
      - "5342:5342"
    env_file:
      - messages_ms.conf

  redis_messages:
    image: redis
    ports:
    - "6389:6389"
    #- "6379:6379"

  messages_ms_worker:
    <<:
      # Building the image
      &messages_ms_worker
      image: "mib-messages:latest"
      build:
        context: ./mib-messages
        dockerfile: Dockerfile

    ports:
      - "5003:5003"
    env_file:
      - messages_ms.conf
    environment:
      - POSTGRES_HOST=db_messages
      - BROKER_URL=redis://redis_messages
      - RESULT_BACKEND=redis://redis_messages
      - USERS_MS_URL=users_ms_worker
      - LOTTERY_MS_URL=lottery_ms_worker
    depends_on:
      - db_messages
      - migrations_messages
      - redis_messages
      - users_ms_worker
      - lottery_ms_worker

  
  migrations_messages:
    #
    # this service is used to apply migrations on db
    #
    <<: *messages_ms_worker
    command: flask db upgrade
    env_file:
      - messages_ms.conf
    environment:
      - POSTGRES_HOST=db_messages
    restart: on-failure
    depends_on:
      - db_messages
  
  celery_worker_messages:
    <<: *messages_ms_worker
    command: ['celery', '-A', 'swagger_server.background', 'worker', '--loglevel=DEBUG']
    env_file:
      - messages_ms.conf
    environment:
      - POSTGRES_HOST=db_messages
      - BROKER_URL=redis://redis_messages
      - RESULT_BACKEND=redis://redis_messages
    depends_on:
      - db_messages
      - redis_messages

  celery_beat_messages:
    <<: *messages_ms_worker
    command: ['celery', '-A', 'swagger_server.background', 'beat', '--loglevel=DEBUG']
    env_file:
      - messages_ms.conf
    environment:
      - POSTGRES_HOST=db_messages
      - BROKER_URL=redis://redis_messages
      - RESULT_BACKEND=redis://redis_messages
    depends_on:
      - db_messages
      - redis_messages
    
  # -------------------------------------------- #
  # Content Filter Microservice                  #
  # -------------------------------------------- #
  db_content_filter:
    image: postgres:13
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/db_content_filter/data
    env_file:
      - content_filter_ms.conf

  content_filter_ms_worker:
    <<:
      # Building the image
      &content_filter_ms_worker
      image: "mib-content_filter:latest"
      build:
        context: ./mib-content-filter
        dockerfile: Dockerfile
    ports:
      - "5005:5005"
    env_file:
      - content_filter_ms.conf
    environment:
      - POSTGRES_HOST=db_content_filter
    depends_on:
      - db_content_filter
      - migrations_content_filter

  migrations_content_filter:
    #
    # this service is used to apply migrations on db
    #
    <<: *content_filter_ms_worker
    command: flask db upgrade
    env_file:
      - content_filter_ms.conf
    environment:
      - POSTGRES_HOST=db_content_filter
    restart: on-failure
    depends_on:
      - db_content_filter

volumes:
  # -------------------------------------------- #
  # Volumes                                      #
  # -------------------------------------------- #

  nginx_conf: null # Nginx configuration volume

  static_contents: null # API Gateway static content volume

  pgdata: null # for maintaing db data
